name: Check Video Source

on:
  # 手动运行
  workflow_dispatch:

jobs:
  check-video:
    runs-on: ubuntu-latest  # 使用Ubuntu最新版本的虚拟机来运行工作

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出仓库代码

    - name: Set up Python
      uses: actions/setup-python@v2  # 设置Python环境
      with:
        python-version: 3.x  # 使用Python 3
    # 安装所需的包
    - name: Install dependencies
      run: |
        pip install selenium requests futures eventlet
        pip install beautifulsoup4
        pip install chardet
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Check video source
      run: |
         python ${{ github.workspace }}/ip_qianxin.py  # 执行Python脚本

