name: Check Video Source

on:
  # 例如，你可以在push到master分支时触发这个工作流
  push:
    branches: [ master ]

jobs:
  check-video:
    runs-on: ubuntu-latest  # 使用Ubuntu最新版本的虚拟机来运行工作

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出仓库代码

    - name: Set up Python
      uses: actions/setup-python@v2  # 设置Python环境
      with:
        python-version: 3.x  # 使用Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ffmpeg-python  # 如果需要的话，安装ffmpeg-python库

    - name: Check video source
      env:
        VIDEO_URL: "your_video_url_here"  # 设置环境变量，这将传递给脚本
      run: |
        python check_video_source.py "$VIDEO_URL"  # 执行Python脚本并传递视频URL作为参数
